export const tsNodeModules: Record<string, () => Promise<string>> =
	// @ts-expect-error
	import.meta.glob<string>(
		[
			'/node_modules/typescript/package.json',
			'/node_modules/typescript/lib/lib.d.ts', // NOTE: Not needed, but just in case
			'/node_modules/typescript/lib/lib.es5.d.ts',
			'/node_modules/typescript/lib/lib.dom.d.ts',
			'/node_modules/typescript/lib/lib.dom.iterable.d.ts',
			'/node_modules/typescript/lib/lib.webworker.importscripts.d.ts',
			'/node_modules/typescript/lib/lib.scripthost.d.ts',
			'/node_modules/typescript/lib/lib.es2015.collection.d.ts',
			'/node_modules/typescript/lib/lib.es2015.generator.d.ts',
			'/node_modules/typescript/lib/lib.es2015.iterable.d.ts',
			'/node_modules/typescript/lib/lib.es2015.promise.d.ts',
			'/node_modules/typescript/lib/lib.es2015.proxy.d.ts',
			'/node_modules/typescript/lib/lib.es2015.reflect.d.ts',
			'/node_modules/typescript/lib/lib.es2015.symbol.d.ts',
			'/node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts',
			'/node_modules/typescript/lib/lib.es2016.array.include.d.ts',
			'/node_modules/typescript/lib/lib.es2017.object.d.ts',
			'/node_modules/typescript/lib/lib.es2017.sharedmemory.d.ts',
			'/node_modules/typescript/lib/lib.es2017.string.d.ts',
			'/node_modules/typescript/lib/lib.es2017.intl.d.ts',
			'/node_modules/typescript/lib/lib.es2017.typedarrays.d.ts',
			'/node_modules/typescript/lib/lib.es2018.asyncgenerator.d.ts',
			'/node_modules/typescript/lib/lib.es2018.asynciterable.d.ts',
			'/node_modules/typescript/lib/lib.es2018.intl.d.ts',
			'/node_modules/typescript/lib/lib.es2018.promise.d.ts',
			'/node_modules/typescript/lib/lib.es2018.regexp.d.ts',
			'/node_modules/typescript/lib/lib.es2019.array.d.ts',
			'/node_modules/typescript/lib/lib.es2019.object.d.ts',
			'/node_modules/typescript/lib/lib.es2019.string.d.ts',
			'/node_modules/typescript/lib/lib.es2019.symbol.d.ts',
			'/node_modules/typescript/lib/lib.es2020.bigint.d.ts',
			'/node_modules/typescript/lib/lib.es2020.intl.d.ts',
			'/node_modules/typescript/lib/lib.es2020.promise.d.ts',
			'/node_modules/typescript/lib/lib.es2020.sharedmemory.d.ts',
			'/node_modules/typescript/lib/lib.es2020.string.d.ts',
			'/node_modules/typescript/lib/lib.es2020.symbol.wellknown.d.ts',
			'/node_modules/typescript/lib/lib.es2021.intl.d.ts',
			'/node_modules/typescript/lib/lib.es2021.promise.d.ts',
			'/node_modules/typescript/lib/lib.es2021.string.d.ts',
			'/node_modules/typescript/lib/lib.es2021.weakref.d.ts',
			'/node_modules/typescript/lib/lib.es2022.d.ts', // NOTE: Not strictly useful? But used for default.
			'/node_modules/typescript/lib/lib.es2022.array.d.ts',
			'/node_modules/typescript/lib/lib.es2022.error.d.ts',
			'/node_modules/typescript/lib/lib.es2022.intl.d.ts',
			'/node_modules/typescript/lib/lib.es2022.object.d.ts',
			'/node_modules/typescript/lib/lib.es2022.regexp.d.ts',
			'/node_modules/typescript/lib/lib.es2022.sharedmemory.d.ts',
			'/node_modules/typescript/lib/lib.es2022.string.d.ts',
			'/node_modules/typescript/lib/lib.es2022.typedarray.d.ts',
			'/node_modules/typescript/lib/lib.decorators.d.ts',
			'/node_modules/typescript/lib/lib.decorators.legacy.d.ts',

			// '/node_modules/web-elements-analyzer/package.json',
			//

			// '/node_modules/web-elements-analyzer/package.json',
			// '/node_modules/web-elements-analyzer/dist/adapters/react.d.ts',
			// '/node_modules/web-elements-analyzer/dist/adapters/type-utilities.d.ts',

			// '/node_modules/lit/package.json',
			// '/node_modules/lit/index.d.ts',
			// '/node_modules/lit/decorators.d.ts',
			// '/node_modules/lit-element/package.json',
			// '/node_modules/lit-element/lit-element.d.ts',
			// '/node_modules/@lit/reactive-element/package.json',
			// '/node_modules/@lit/reactive-element/reactive-element.d.ts',
			// '/node_modules/@lit/reactive-element/css-tag.d.ts',
			// '/node_modules/@lit/reactive-element/reactive-controller.d.ts',
			// '/node_modules/@lit/reactive-element/decorators/base.d.ts',
			// '/node_modules/@lit/reactive-element/decorators/custom-element.d.ts',
			// '/node_modules/@lit/reactive-element/decorators/property.d.ts',
			// '/node_modules/@lit/reactive-element/decorators/state.d.ts',
			// '/node_modules/@lit/reactive-element/decorators/query.d.ts',
			// '/node_modules/@lit/reactive-element/decorators/query-all.d.ts',
			// '/node_modules/@lit/reactive-element/decorators/query-async.d.ts',
			// '/node_modules/@lit/reactive-element/decorators/query-assigned-nodes.d.ts',
			// '/node_modules/@lit/reactive-element/decorators/query-assigned-elements.d.ts',
			// '/node_modules/@lit/reactive-element/decorators/event-options.d.ts',
			// '/node_modules/lit-html/package.json',
			// '/node_modules/lit-html/lit-html.d.ts',
			// '/node_modules/lit-html/directive.d.ts',
			// '/node_modules/lit-html/is-server.d.ts',

			// '/node_modules/@types/trusted-types/package.json',
			// '/node_modules/@types/trusted-types/lib/index.d.ts',

			// '/node_modules/@types/react/package.json',
			// '/node_modules/@types/react/index.d.ts',
			// '/node_modules/@types/react/global.d.ts',
			// '/node_modules/@types/react/jsx-runtime.d.ts',

			// // '/node_modules/solid-js/package.json',
			// '/node_modules/solid-js/jsx-runtime.d.ts',
			// '/node_modules/solid-js/types/jsx.d.ts',
			// '/node_modules/solid-js/types/index.d.ts',
			// // '/node_modules/solid-js/**/*.d.ts',

			// '/node_modules/csstype/index.d.ts',

			// '/node_modules/@shoelace-style/shoelace/package.json',
			// '/node_modules/@shoelace-style/shoelace/dist/events/*.d.ts',
			// '/node_modules/@shoelace-style/shoelace/dist/shoelace.d.ts',
			// // '/node_modules/@shoelace-style/shoelace/dist/custom-elements.json',
			// // // TODO: Cherry pick
			// // '/node_modules/@shoelace-style/shoelace/dist/**/*.d.ts',
			// '/node_modules/@shoelace-style/shoelace/dist/components/dialog/dialog.d.ts',
		],
		{ query: 'raw', import: 'default' }, // NOTE: Might want to lazy load
	);

export const litNodeModulesBase: Record<string, () => Promise<string>> =
	// @ts-expect-error
	import.meta.glob<string>(
		[
			'/node_modules/lit/package.json',
			'/node_modules/lit/index.d.ts',
			'/node_modules/lit/decorators.d.ts',
			'/node_modules/lit-element/package.json',
			'/node_modules/lit-element/lit-element.d.ts',
			'/node_modules/@lit/reactive-element/package.json',
			'/node_modules/@lit/reactive-element/reactive-element.d.ts',
			'/node_modules/@lit/reactive-element/css-tag.d.ts',
			'/node_modules/@lit/reactive-element/reactive-controller.d.ts',
			'/node_modules/@lit/reactive-element/decorators/base.d.ts',
			'/node_modules/@lit/reactive-element/decorators/custom-element.d.ts',
			'/node_modules/@lit/reactive-element/decorators/property.d.ts',
			'/node_modules/@lit/reactive-element/decorators/state.d.ts',
			'/node_modules/@lit/reactive-element/decorators/query.d.ts',
			'/node_modules/@lit/reactive-element/decorators/query-all.d.ts',
			'/node_modules/@lit/reactive-element/decorators/query-async.d.ts',
			'/node_modules/@lit/reactive-element/decorators/query-assigned-nodes.d.ts',
			'/node_modules/@lit/reactive-element/decorators/query-assigned-elements.d.ts',
			'/node_modules/@lit/reactive-element/decorators/event-options.d.ts',
			'/node_modules/lit-html/package.json',
			'/node_modules/lit-html/lit-html.d.ts',
			'/node_modules/lit-html/directive.d.ts',
			'/node_modules/lit-html/is-server.d.ts',

			'/node_modules/@types/trusted-types/package.json',
			'/node_modules/@types/trusted-types/lib/index.d.ts',
		],
		{ query: 'raw', import: 'default' },
	);
